version: '3.7'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: hotel-backend
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/hotel
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - "8081:8080"
    depends_on:
      - db

  db:
    image: "postgres:15.1"
    container_name: hotel-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=hotel
    ports:
      - "3333:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: